In [1]:
import torch
import numpy as np
import time

device = 'cuda'  if torch.cuda.is_available() else 'cpu'
device
block_size = 8
batch_size =4

In [3]:
with open('wizard_of_oz.txt','r',encoding='utf-8') as f:
    text = f.read()
print(len(text))
chars = sorted(set(text))
print(chars)
print(len(chars))
vocab_size = len(chars)

234112
['\n', ' ', '!', '"', '#', '$', '%', '&', "'", '(', ')', '*', ',', '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '—', '‘', '’', '“', '”', '•', '™', '\ufeff']
92


In [6]:
string_to_int = {ch:i for i,ch in enumerate(chars)}
int_to_string = {i:ch for i,ch in enumerate(chars)}
encode = lambda s: [string_to_int[ch] for ch in s]
decode = lambda x: ''.join([int_to_string[i] for i in x])

data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape)
print(data[:100])

torch.Size([234112])
tensor([91, 48, 65, 62,  1, 44, 75, 72, 67, 62, 60, 77,  1, 35, 78, 77, 62, 71,
        59, 62, 75, 64,  1, 62, 30, 72, 72, 68,  1, 72, 63,  1, 48, 65, 62,  1,
        51, 72, 71, 61, 62, 75, 63, 78, 69,  1, 51, 66, 83, 58, 75, 61,  1, 72,
        63,  1, 43, 83,  0,  1,  1,  1,  1,  0, 48, 65, 66, 76,  1, 62, 59, 72,
        72, 68,  1, 66, 76,  1, 63, 72, 75,  1, 77, 65, 62,  1, 78, 76, 62,  1,
        72, 63,  1, 58, 71, 82, 72, 71, 62,  1])


In [13]:
n = int(0.8*len(data))
train_data = data[:n]
val_data = data[n:]

def get_batch(split):
  data = train_data if split == 'train' else val_data
  ix =torch.randint(len(data)-block_size, (batch_size,))
  print(ix)
  x = torch.stack([data[i:i+block_size]for i in ix])
  y = torch.stack([data[i+1:i+block_size+1]for i in ix])
  return x,y
x, y = get_batch('train')
print('inputs:')
print(x)
print('targets:')
print(y)

tensor([142022,  37743,  27836,  16048])
inputs:
tensor([[77,  1, 58, 71, 61,  1, 76, 65],
        [60, 75, 72, 80, 14,  0,  0, 48],
        [ 1, 59, 62, 69, 72, 71, 64, 62],
        [ 1, 80, 65, 62, 75, 62,  1, 37]])
targets:
tensor([[ 1, 58, 71, 61,  1, 76, 65, 72],
        [75, 72, 80, 14,  0,  0, 48, 65],
        [59, 62, 69, 72, 71, 64, 62, 61],
        [80, 65, 62, 75, 62,  1, 37,  1]])


In [7]:
start_time = time.time()
zeros = torch.zeros(1,1)
end_time=time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.10f}")

0.0010936260
